import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans, Barlow } from "next/font/google";
import "../node_modules/bootstrap/dist/css/bootstrap.min.css"
import "./globals.css";
import Header from "./Components/Header";
import Footer from "./Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const open_sans = Open_Sans({
  variable: "--font-Open_Sans",
  subsets: ["latin"],
});

const barlow = Barlow({
  weight: "400",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased ${open_sans.className}`}>
       
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
